---
- block:
    - name: Ensure that the strongswan group exist
      group: name=strongswan state=present

    - name: Ensure that the strongswan user exist
      user: name=strongswan group=strongswan state=present

    - include_tasks: ubuntu.yml
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - include_tasks: freebsd.yml
      when: ansible_distribution == 'FreeBSD'

    - include_tasks: arch.yml
      when: ansible_distribution == 'Archlinux'

    - name: Install strongSwan
      package: name=strongswan state=present

    - include_tasks: ipsec_configuration.yml
    - include_tasks: openssl.yml
      tags: update-users
    - include_tasks: distribute_keys.yml
    - include_tasks: client_configs.yml
      delegate_to: localhost
      become: no
      tags: update-users

    - meta: flush_handlers

    - name: strongSwan started
      service: name=strongswan state=started
  rescue:
    - debug: var=fail_hint
      tags: always
    - fail:
      tags: always
