---
- name: Include tasks for Ubuntu
  include_tasks: ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


- name: dnscrypt-proxy ip-blacklist configured
  template:
    src: ip-blacklist.txt.j2
    dest: "{{ config_prefix | default('/') }}etc/dnscrypt-proxy/ip-blacklist.txt"
    mode: '0644'
  notify:
    - restart dnscrypt-proxy

- name: dnscrypt-proxy configured
  template:
    src: dnscrypt-proxy.toml.j2
    dest: "{{ config_prefix | default('/') }}etc/dnscrypt-proxy/dnscrypt-proxy.toml"
    mode: '0644'
  notify:
    - restart dnscrypt-proxy

- name: Include DNS adblocking tasks
  import_tasks: dns_adblocking.yml
  when: algo_dns_adblocking

- meta: flush_handlers

- name: dnscrypt-proxy enabled and started
  service:
    name: dnscrypt-proxy
    state: started
    enabled: true

- name: Ubuntu | Disable dnscrypt-proxy socket activation after service start
  systemd:
    name: dnscrypt-proxy.socket
    state: stopped
    enabled: false
    masked: true
  failed_when: false
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
