---

- name: Check the system
  raw: uname -a
  register: OS

- name: Ubuntu pre-tasks
  include_tasks: ubuntu.yml
  when: '"Ubuntu" in OS.stdout or "Linux" in OS.stdout'

- name: FreeBSD pre-tasks
  include_tasks: freebsd.yml
  when: '"FreeBSD" in OS.stdout'

- name: Arch pre-tasks
  include_tasks: arch.yml
  when: '"ARCH" in OS.stdout'


- include_tasks: facts/main.yml
