---

- name: Wait until SSH becomes ready...
  local_action:
    module: wait_for
    port: 22
    host: "{{ cloud_instance_ip }}"
    search_regex: "OpenSSH"
    delay: 10
    timeout: 320
    state: present

- name: A short pause, in order to be sure the instance is ready
  pause:
    seconds: 10

- include: local_ssh.yml
