---
- name: WireGuard apple mobileconfig generated
  template:
    src: mobileconfig.j2
    dest: "{{ wireguard_config_path }}/apple/{{ system }}/{{ item }}.mobileconfig"
    mode: "0600"
  loop: "{{ wireguard_users }}"
  loop_control:
    index_var: index
  when: item in users
